# type: ignore

"""
02_generated_methods.py

Demonstrates the methods auto-generated by dataclasses.

Dataclasses automatically create __init__, __repr__, and __eq__
for simple data models.
"""

from dataclasses import dataclass


# ============================================================
# 1. GENERATED __init__
# ============================================================

@dataclass
class Product:
    """A product model."""

    name: str
    price: float


p1 = Product("Laptop", 80000.0)
print(p1)

"""
Product(name='Laptop', price=80000.0)
This string is generated by __repr__.
"""


# ============================================================
# 2. GENERATED __eq__
# ============================================================

p2 = Product("Laptop", 80000.0)
print(p1 == p2)

"""
Dataclass equality compares each field by value.
So two products with the same values are equal.
"""


# ============================================================
# 3. GENERATED __hash__
# ============================================================

# Dataclasses are hashable by default only if they are frozen and
# all fields are hashable.

@dataclass(frozen=True)
class Point:
    x: int
    y: int


print(hash(Point(1, 2)))

"""
Frozen dataclasses can be hashed because they are immutable.
"""


# ============================================================
# KEY TAKEAWAYS
# ============================================================

# - dataclass generates constructor logic automatically
# - __repr__ gives clean debugging output
# - __eq__ compares by value
# - additional methods may be generated depending on configuration
